######################################################################
# Automatically generated by qmake (2.01a) ?? 23. ??? 21:47:18 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += checker.h compiler.h submission.h submissionprocess.h
SOURCES += checker.cpp \
           compiler.cpp \
           main.cpp \
           submission.cpp \
           submissionprocess.cpp
